export const TOGGLE_MENU = 'TOGGLE_MENU'
export const TOGGLE_SEARCH = 'TOGGLE_SEARCH'

export const CATPURE_SEARCH_INPUT = 'CATPURE_SEARCH_INPUT'

export const FETCH_SEARCH_RESULT_SUCCESS = 'FETCH_SEARCH_RESULT_SUCCESS'
export const FETCH_SEARCH_RESULT_ERROR = 'FETCH_SEARCH_RESULT_ERROR'

export const FETCH_HOME_PAGE_SONGS = 'FETCH_HOME_PAGE_SONGS'
export const FETCH_HOME_PAGE_SONGS_SUCCESS = 'FETCH_HOME_PAGE_SONGS_SUCCESS'
export const FETCH_HOME_PAGE_SONGS_ERROR = 'FETCH_HOME_PAGE_SONGS_ERROR'